services:
  mercure:
    image: dunglas/mercure
    ports:
      - "3000:80"
    environment:
      - MERCURE_PUBLISHER_JWT_KEY=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - MERCURE_SUBSCRIBER_JWT_KEY=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - MERCURE_EXTRA_DIRECTIVES=cors_origins http://localhost:8000
      - MERCURE_ALLOW_ANONYMOUS=1
      - SERVER_NAME=:80
    volumes:
      - mercure_data:/data

volumes:
  mercure_data:
