services:
  mercure:
    image: dunglas/mercure
    ports:
      - "3000:80"
    environment:
      - MERCURE_PUBLISHER_JWT_KEY=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - MERCURE_SUBSCRIBER_JWT_KEY=MySecretKey
      - MERCURE_ALLOW_ANONYMOUS=0
      - SERVER_NAME=:80
      - MERCURE_EXTRA_DIRECTIVES=cors_origins "http://localhost:8000"
      - MERCURE_COOKIE_SECURE=false
      - MERCURE_COOKIE_SAME_SITE=lax
      - MERCURE_CORS_ALLOWED_ORIGINS=* 
      - MERCURE_CORS_ALLOW_CREDENTIALS=true
      - MERCURE_LOG_LEVEL=debug
      - MERCURE_COOKIE_AUTHENTICATION=1
    volumes:
      - mercure_data:/data
volumes:
  mercure_data: